// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk62v9u2aLClQYqzFREqEhDRNyFdEjdyA',
    appId: '1:115904987507:web:7baed4a5e27ee87b00c506',
    messagingSenderId: '115904987507',
    projectId: 'soundpilot-57e94',
    authDomain: 'soundpilot-57e94.firebaseapp.com',
    storageBucket: 'soundpilot-57e94.firebasestorage.app',
    measurementId: 'G-J5YN0KDLPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1RKGeE4Pi1VDR_rNbxeZXKeIWy6NU4g',
    appId: '1:115904987507:android:5323c12be72f9b2900c506',
    messagingSenderId: '115904987507',
    projectId: 'soundpilot-57e94',
    storageBucket: 'soundpilot-57e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyHt56UXHaWht87rhRxXhfEnw9hZKpqJg',
    appId: '1:115904987507:ios:5f7762815a2f34ba00c506',
    messagingSenderId: '115904987507',
    projectId: 'soundpilot-57e94',
    storageBucket: 'soundpilot-57e94.firebasestorage.app',
    iosClientId: '115904987507-p0a1ob00sfiprn4jnoae54m7qvnks3hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundpilotApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyHt56UXHaWht87rhRxXhfEnw9hZKpqJg',
    appId: '1:115904987507:ios:5f7762815a2f34ba00c506',
    messagingSenderId: '115904987507',
    projectId: 'soundpilot-57e94',
    storageBucket: 'soundpilot-57e94.firebasestorage.app',
    iosClientId: '115904987507-p0a1ob00sfiprn4jnoae54m7qvnks3hn.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundpilotApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk62v9u2aLClQYqzFREqEhDRNyFdEjdyA',
    appId: '1:115904987507:web:dd4d8e5ce1f3989f00c506',
    messagingSenderId: '115904987507',
    projectId: 'soundpilot-57e94',
    authDomain: 'soundpilot-57e94.firebaseapp.com',
    storageBucket: 'soundpilot-57e94.firebasestorage.app',
    measurementId: 'G-M1ZRY56QSM',
  );
}
