import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'core/app_logger.dart'; // Our logger from before
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  /// Ensures that all widgets and engine bindings are ready.
  /// This must be called before initializing Firebase.
  WidgetsFlutterBinding.ensureInitialized();

  try {
    /// Connects the app to Firebase using the platform-specific options.
    /// DefaultFirebaseOptions comes from the generated firebase_options.dart file.
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    logger.i("Main: Firebase initialized successfully");
  } catch (e) {
    logger.e("Main: Failed to initialize Firebase", error: e);
  }

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SoundPilot Application',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        useMaterial3: true, // As specified in pubspec.yaml
      ),
      home: const Scaffold(
        body: Center(
          child: Text('Firebase is initialized!'),
        ),
      ),
    );
  }
}